// src/pages/ExecutiveSummary.tsx
// AI-generated plain-English inventory briefing for non-technical business users

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "../services/api";

interface SummaryContext {
  total_products: number;
  stockout_count: number;
  critical_count: number;
  healthy_count: number;
  total_stock_value: number;
  stockout_names: string[];
  critical_names: string[];
  demand_trend_pct: number;
  generated_date: string;
  recent_anomalies: {
    product: string;
    severity: string;
    date: string;
  }[];
  top_forecasts: {
    product: string;
    total_30d: number;
    avg_daily: number;
  }[];
}

interface SummaryResponse {
  summary: string;
  context: SummaryContext;
  source: "claude" | "fallback";
}

export default function ExecutiveSummary() {
  const [lastRefreshed, setLastRefreshed] = useState<Date | null>(null);

  const { data, isLoading, isError, refetch, isFetching } =
    useQuery<SummaryResponse>({
      queryKey: ["executive-summary"],
      queryFn: async () => {
        const res = await api.get("/summary/executive");
        setLastRefreshed(new Date());
        return res.data;
      },
      staleTime: 5 * 60 * 1000, // 5 minutes — don't spam the Claude API
      retry: 1,
    });

  const ctx = data?.context;

  const statusColor = (stockouts: number, critical: number) => {
    if (stockouts > 0) return { bg: "bg-red-500/10", border: "border-red-500/30", dot: "bg-red-400", label: "Needs Attention", text: "text-red-400" };
    if (critical > 0)  return { bg: "bg-amber-500/10", border: "border-amber-500/30", dot: "bg-amber-400", label: "Monitor Closely", text: "text-amber-400" };
    return { bg: "bg-emerald-500/10", border: "border-emerald-500/30", dot: "bg-emerald-400", label: "All Good", text: "text-emerald-400" };
  };

  const status = ctx ? statusColor(ctx.stockout_count, ctx.critical_count) : null;

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 p-6">
      <div className="max-w-4xl mx-auto">

        {/* Header */}
        <div className="flex items-start justify-between mb-8">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-9 h-9 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-lg">
                📋
              </div>
              <h1 className="text-2xl font-bold text-white">Executive Summary</h1>
            </div>
            <p className="text-gray-400 text-sm">
              Plain-English AI briefing — updated {lastRefreshed ? lastRefreshed.toLocaleTimeString() : "on load"}
            </p>
          </div>

          <button
            onClick={() => refetch()}
            disabled={isFetching}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400 hover:bg-amber-500/20 transition-all text-sm font-medium disabled:opacity-50"
          >
            <span className={isFetching ? "animate-spin" : ""}>↻</span>
            {isFetching ? "Generating..." : "Refresh Summary"}
          </button>
        </div>

        {/* Loading */}
        {isLoading && (
          <div className="rounded-2xl border border-white/10 bg-white/5 p-10 text-center">
            <div className="w-12 h-12 rounded-full border-2 border-amber-500/30 border-t-amber-400 animate-spin mx-auto mb-4" />
            <p className="text-gray-400 text-sm">Claude is reading your inventory data...</p>
          </div>
        )}

        {/* Error */}
        {isError && (
          <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-8 text-center">
            <p className="text-red-400 font-medium mb-2">Could not generate summary</p>
            <p className="text-gray-400 text-sm">Check that ANTHROPIC_API_KEY is set on Render.</p>
          </div>
        )}

        {/* Content */}
        {data && ctx && (
          <div className="space-y-6">

            {/* Status bar */}
            <div className={`rounded-2xl border ${status!.bg} ${status!.border} p-5 flex items-center justify-between`}>
              <div className="flex items-center gap-3">
                <div className={`w-3 h-3 rounded-full ${status!.dot} animate-pulse`} />
                <span className={`font-semibold ${status!.text}`}>{status!.label}</span>
                <span className="text-gray-400 text-sm">— {ctx.generated_date}</span>
              </div>
              {data.source === "claude" && (
                <div className="flex items-center gap-2 text-xs text-gray-500">
                  <span>✦</span>
                  <span>Generated by Claude AI</span>
                </div>
              )}
            </div>

            {/* KPI row */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: "Stock Value", value: `$${(ctx.total_stock_value / 1000).toFixed(1)}K`, sub: "total portfolio" },
                { label: "Out of Stock", value: ctx.stockout_count, sub: "need orders now", alert: ctx.stockout_count > 0 },
                { label: "Running Low", value: ctx.critical_count, sub: "near reorder point", warn: ctx.critical_count > 0 },
                {
                  label: "Demand Trend",
                  value: `${ctx.demand_trend_pct >= 0 ? "+" : ""}${ctx.demand_trend_pct}%`,
                  sub: "vs last week",
                  up: ctx.demand_trend_pct > 0
                },
              ].map((kpi, i) => (
                <div
                  key={i}
                  className={`rounded-xl border p-4 ${
                    kpi.alert ? "border-red-500/30 bg-red-500/10"
                    : kpi.warn ? "border-amber-500/30 bg-amber-500/10"
                    : "border-white/10 bg-white/5"
                  }`}
                >
                  <div className={`text-2xl font-bold mb-1 ${
                    kpi.alert ? "text-red-400"
                    : kpi.warn ? "text-amber-400"
                    : "text-white"
                  }`}>{kpi.value}</div>
                  <div className="text-xs font-medium text-gray-300">{kpi.label}</div>
                  <div className="text-xs text-gray-500">{kpi.sub}</div>
                </div>
              ))}
            </div>

            {/* AI Summary text */}
            <div className="rounded-2xl border border-white/10 bg-white/5 p-7">
              <div className="flex items-center gap-2 mb-5 pb-4 border-b border-white/10">
                <span className="text-amber-400">✦</span>
                <span className="text-sm font-semibold text-gray-300 uppercase tracking-wider">Today's Briefing</span>
              </div>
              <div className="prose prose-invert prose-sm max-w-none">
                {data.summary.split("\n\n").filter(Boolean).map((para, i) => (
                  <p key={i} className="text-gray-200 leading-relaxed mb-4 last:mb-0 text-base">
                    {para}
                  </p>
                ))}
              </div>
            </div>

            {/* Alerts + Forecasts side by side */}
            <div className="grid md:grid-cols-2 gap-4">

              {/* Recent alerts */}
              <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
                <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wider mb-4">
                  Recent Alerts
                </h3>
                {ctx.recent_anomalies.length === 0 ? (
                  <p className="text-gray-500 text-sm">No significant alerts in the last 14 days.</p>
                ) : (
                  <div className="space-y-3">
                    {ctx.recent_anomalies.map((a, i) => (
                      <div key={i} className="flex items-start gap-3">
                        <span className={`text-xs px-2 py-1 rounded-lg font-bold mt-0.5 ${
                          a.severity === "HIGH"
                            ? "bg-red-500/20 text-red-400"
                            : "bg-amber-500/20 text-amber-400"
                        }`}>{a.severity}</span>
                        <div>
                          <div className="text-sm text-white font-medium">{a.product}</div>
                          <div className="text-xs text-gray-500">{a.date}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Top forecasts */}
              <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
                <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wider mb-4">
                  Highest Demand (Next 30 Days)
                </h3>
                <div className="space-y-3">
                  {ctx.top_forecasts.map((f, i) => (
                    <div key={i} className="flex items-center justify-between">
                      <div className="text-sm text-white truncate mr-3">{f.product}</div>
                      <div className="text-right shrink-0">
                        <div className="text-sm font-bold text-amber-400">{f.total_30d.toLocaleString()} units</div>
                        <div className="text-xs text-gray-500">{f.avg_daily}/day avg</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Footer note */}
            <p className="text-xs text-gray-600 text-center pb-2">
              This summary is generated from live inventory data. Refresh any time to get an updated briefing.
            </p>

          </div>
        )}
      </div>
    </div>
  );
}